language: python
python: 3.4
env:
  matrix:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=lint
  global:
  - AWS_ACCESS_KEY_ID=AKIAJ64FKAB5DNJPF5HA
  - secure: g/ta2yudfA55ruxd+GHxYQUd39OM/hoEhNp0KgPm3QINaXwaB6C9eQ31qOi/i9OiSjmVwISE+yUaPtQP2jtbYnkS/SHiRNvzhfA+mPrT0n0hoVSNIlxl94E8hoPBZr2jlYVQ6dIuT98mIRYJu/wiGHDQCuar6znpiKFB1/gyUszvZxAxHJIe5EcjuXWFnre91b96tNkZRKJZv+Jst0CkknVcKAZ4kmC/o5Z1hr5VaMekRV5SKf+vMEfVc+W9VktqDBgKwaFIwWqSgQFk5LOnPr/EZq8mrqPpa+LFaLiQpDGDAdaVEM0/A3dzx3YnYoBFNr5hmCtoCLWccxC+diaw3kZuTX6olxn8cbRCVf8lu4JuJKFU5CgTLS7NBH3Rpk4iRE7C9v4W+QKjw3CJxLCMoMqQCbYx6GjzjZYbZBA6jvaS6ZFe41N6egA0SpNvKtfYU9TR7lNVwGehRIY9kycOEX5ZQInkqILxz5YHrkMNfICdLY+rYFBDvgNAOZxYR1tLaOG9jYuUbBOLVRZz78wkPrXynquay6HZn7AxBxOdnvGQAkINvo40Lx/MWdZ88o3f/th838cpPCxBRQZ5Kn3RkHNhGHwUJadsbaOLnKrj3ISaTOvq0brA1mxJFyJwoVrn+rFs80CWRonQ5lQeaOHf0p1flH7j+TFhl/INkvXsf7Y=  # PGPASSWORD
  - secure: w8uDiHUyB1QdIJLiGLvEusfcymJdwtrJFhCdX77vWObD8mdThEwNZBcYfceEl1DCzQDgsME8y9aFcx8/5Blx+lbeKUtqBxj1XyMYRZTIu9t5wIK1YNLc7+cXk1dSfdaeTO/dCy9UMFGo9vdKr3vg2Pcs4VYXnBF7gUVu6dFKNXSO++JZxeq61ISAGyWdyUrFWr1I3pehevKIenUqx0Pj7aSHl6ROcBBiKXcgC8z0xQXK1Y5u7qfclbFMtOcs+lnjSrUpQfZ2rHxHuHO2tvkfDIqdl/u8st7wJGVxZmufqA5ydF5OJfdb3CKLJYsxf7A3hcnAbuSvsWyuvCcoCwGbTBHsZQzDnBJY+/56t2MhLTE/rYYP5h9troJ4i/68I/2uLe0bXz4MIypIgg8ivbKwYhRD6BqN+XJ3p+MdHvCcMj/qT7/NWOSDv1RxlPsZ+P4CeORMYHpLbz5ejZkoCgy5vmw1jl7lQf7mDO+vQMRSrNc03RQbDcek1sQ4dFx1Ch+z7c32wSSp0f595MpR1LHNVbJZKdukpszUn6dM6cG/GTxYKEFMNvBi+fQTTcCFPCFHPtlpKwi2DXsk3L2vlCFGiVhU09Pn5VKlaiBNtTp+0TiiRIqC3PUCM6e0OOoAxd2+v3k25hfuwEbyfsIbpvRV40Piwjz+nada8Rxw/Ptu2dg=  # AWS_SECRET_ACCESS_KEY
install:
- pip install tox
script:
- tox -e $TOX_ENV
